log:
  level: DEBUG
api:
  dashboard: true
providers:
  docker:
    exposedByDefault: false
entryPoints:
  http:
    address: ":80"


experimental:
  plugins:
    keycloakopenid:
      moduleName: "github.com/Gwojda/keycloakopenid"
      version: "v0.1.34"
    headauth:
      moduleName: "github.com/poloyacero/headauth"
      version: "v0.0.1"